FROM mcr.microsoft.com/dotnet/core/aspnet:5.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/core/sdk:5.0 AS build
WORKDIR /src
COPY ["Mine.Commerce.Identity.csproj", "./"]
RUN dotnet restore "./Mine.Commerce.Identity.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "Mine.Commerce.Identity.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Mine.Commerce.Identity.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Mine.Commerce.Identity.dll"]
